language: java

jobs:
  include:
    - state: build
      name: Calling Ant to create distribution
      script: ant release
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true